### ISSUE TITLE
Don't work on Mac and spam with ERROR logs

### ISSUE THREAD

**Issue by Kirillabaskin** [xvzc/SpoofDPI#70] opened 2024-07-30 19:54 UTC
Hello,
After running spoof-dpi internet connection stop working
In terminal I see only error logs

<img width="512" alt="Снимок экрана 2024-07-30 в 22 51 19" src="https://github.com/user-attachments/assets/b94c16ea-03b6-4c06-8b7a-0248b330d611">

**OS**: macOS Sonoma 14.4
**Installation**: via binary

Maybe somebody fixed this problem ? Or I missed something ?

**Comment by xvzc** [comment] 2024-07-31 07:18
Did you use the default dns `8.8.8.8`? Maybe it is blocked in your region?

**Comment by Kirillabaskin** [comment] 2024-07-31 07:52
Yes, I used default dns and I'm from Russia. While looking for valid dns I found that my internet-provider blocking port 53 everywhere except allowed dns addresses. After changing dns on one of the list internet started to work. But I still see this in logs
<img width="577" alt="Снимок экрана 2024-07-31 в 10 49 38" src="https://github.com/user-attachments/assets/9a28d38f-5d60-4269-b125-a3d5c16e1a2b">

**Comment by xvzc** [comment] 2024-07-31 08:21
Give me the result of
```bash
nslookup
> server 217.10.44.35
> rr3---sn-hgn7yn7s.googlevideo.com
```

**Comment by Kirillabaskin** [comment] 2024-07-31 08:27
\> server 217.10.44.35
Default server: 217.10.44.35
Address: 217.10.44.35#53
\> rr3---sn-hgn7yn7s.googlevideo.com
Server:		217.10.44.35
Address:	217.10.44.35#53

Non-authoritative answer:
rr3---sn-hgn7yn7s.googlevideo.com	canonical name = rr3.sn-hgn7yn7s.googlevideo.com.
Name:	rr3.sn-hgn7yn7s.googlevideo.com
Address: 74.125.11.200

**Comment by xvzc** [comment] 2024-07-31 11:55
Could not reproduce. Please try running `spoof-dpi` on the latest commit and debug.
the dns resolving part is here

https://github.com/xvzc/SpoofDPI/blob/6f151e7038c8c6eb3529129451065f649a92ee08/dns/dns.go#L49-L61

**Comment by nn23** [comment] 2024-08-01 07:11
I have got same issue, spoofdpi version is 0.10.2 with flags  `-enable-doh --url=googlevideo.com -debug`
Firefox uses nextdns.io as DoH provider. 

```
DEBU[2024-08-01T09:58:23+03:00] [PROXY] Request from 127.0.0.1:50470

CONNECT r7---sn-jvhnu5g-n8v6.googlevideo.com:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: r7---sn-jvhnu5g-n8v6.googlevideo.com:443
 
ERRO[2024-08-01T09:58:23+03:00] [PROXY] Error while dns lookup: r7---sn-jvhnu5g-n8v6.googlevideo.com could not resolve the domain 
DEBU[2024-08-01T09:58:25+03:00] [HTTPS] Error reading from 127.0.0.1:50467 timed out 
DEBU[2024-08-01T09:58:25+03:00] [HTTPS] Closing client Connection.. 127.0.0.1:50467 
```

nslookup results:
`nslookup r7---sn-jvhnu5g-n8v6.googlevideo.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
r7---sn-jvhnu5g-n8v6.googlevideo.com	canonical name = r7.sn-jvhnu5g-n8v6.googlevideo.com.
Name:	r7.sn-jvhnu5g-n8v6.googlevideo.com
Address: 212.188.49.82`

**Comment by xvzc** [comment] 2024-08-01 07:56
Does this actually occur any inconvenience on your browsers? seems like temporary dns error. if this doesn't occur any wrong behavior i can just hide the log.

**Comment by Kirillabaskin** [comment] 2024-08-01 16:20
looks like I found solution for me
> spoof-dpi -enable-doh --window-size 0

Even error logs do not show any more. I think this issue can be closed

**Closed** 2024-08-01 16:22 UTC
Labels: bug
